[package]
name = "cio"
version = "0.1.0"
edition = "2021"

[dependencies]
env_logger = "0.9.0"
log = "0.4.14"
serde = { version = "1.0.136", features = ["derive"] }
serde_json = "1.0.78"
tokio = { version = "1.16.1", features = ["full"] }
